# Metodo K-Means

In [2]:
import numpy as np

### Generamos Datos

In [3]:
data=np.random.random(90).reshape(30,3) #reshape(30 datos, 3 columnas)
data

array([[0.19050508, 0.90139881, 0.94117678],
       [0.51915442, 0.66157057, 0.68156419],
       [0.28392383, 0.38503637, 0.09937653],
       [0.20606403, 0.57080739, 0.81398429],
       [0.83764254, 0.55918775, 0.25934527],
       [0.95610391, 0.4149112 , 0.91971545],
       [0.73850166, 0.81775754, 0.82196685],
       [0.62730941, 0.98922111, 0.60371479],
       [0.04105036, 0.20204215, 0.41351859],
       [0.1188208 , 0.8747862 , 0.93792254],
       [0.95865648, 0.44316393, 0.26154804],
       [0.79102759, 0.2470063 , 0.42712672],
       [0.94133215, 0.9348285 , 0.63740727],
       [0.73233399, 0.80287317, 0.30761651],
       [0.83572419, 0.0561044 , 0.71858901],
       [0.14403431, 0.76291369, 0.98453283],
       [0.99814899, 0.523527  , 0.35874647],
       [0.71697502, 0.51917264, 0.83709073],
       [0.27790543, 0.71612826, 0.18213455],
       [0.37007334, 0.7070518 , 0.39339978],
       [0.51464422, 0.63448191, 0.4851268 ],
       [0.40266471, 0.25058962, 0.16946002],
       [0.

### Creamos centroides de los clusters

In [5]:
centroide_1=np.random.choice(range(len(data)))
centroide_2=np.random.choice(range(len(data)))
clust_centers=np.vstack((data[centroide_1],data[centroide_2]))
clust_centers

array([[0.27790543, 0.71612826, 0.18213455],
       [0.23337141, 0.39982555, 0.67616165]])

### Generamos clusters

In [6]:
from scipy.cluster.vq import vq

In [15]:
clusters=vq(data,clust_centers)
clusters[0] #array que dictaminna a que cluster pertenece cada dato
clusters[1] #distancias al varicentro del cluster
clusters

(array([1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
        1, 0, 1, 1, 0, 1, 1, 0], dtype=int32),
 array([0.56889918, 0.38757138, 0.34133114, 0.22130424, 0.5864277 ,
        0.76281603, 0.67162704, 0.61187641, 0.38090292, 0.55428172,
        0.73772489, 0.62956535, 0.83380936, 0.47934926, 0.69481881,
        0.48467195, 0.76618392, 0.52346379, 0.        , 0.23067358,
        0.39308482, 0.4821325 , 0.81302307, 0.48141664, 0.41474771,
        0.        , 0.45427317, 0.47930977, 0.58898044, 0.32147308]))

In [16]:
from scipy.cluster.vq import kmeans

In [23]:
clusters_2=kmeans(data,2)
clusters_2

(array([[0.47852079, 0.73400022, 0.70595456],
        [0.5802722 , 0.33071212, 0.31036566]]), 0.38309698932158354)