In [9]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [10]:
dataset=pd.read_csv('../python-ml-course/datasets/ads/Advertising.csv')

## 1- Conocer con que variables es mas optimo el modelo

In [11]:
all_variables=dataset[['TV','Radio','Newspaper']]
variable_deseada=dataset['Sales']

estimador=SVR(kernel='linear')
selector=RFE(estimador,2,step=1) #El 2 representa el numero de variables que queremos para el modelo predictivo
selector=selector.fit(all_variables,variable_deseada)

In [12]:
selector.support_  #Variables que se escogieron en base a variables_predictoras

array([ True,  True, False])

## 2- Usar variables para crear modelo predictivo

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
var_predictoras=all_variables[['TV','Radio']] #variables basadas en el selector.support_

In [15]:
lm=LinearRegression()
lm.fit(var_predictoras,variable_deseada)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
lm.intercept_ #ordenada del origen

2.921099912405138

In [17]:
lm.coef_ #coeficientes 

array([0.04575482, 0.18799423])

In [18]:
lm.score(var_predictoras,variable_deseada) #r2 ajustado

0.8971942610828956

In [19]:
sales_predict=2.921099912405138+0.04575482*dataset['TV']+0.18799423*dataset['Radio']
sales_predict

0      20.555466
1      12.345363
2      12.337018
3      17.617117
4      13.223909
5      12.512085
6      11.718213
7      12.105516
8       3.709379
9      12.551698
10      7.035860
11     17.256521
12     10.608662
13      8.810951
14     18.444669
15     20.828917
16     12.903866
17     23.241078
18      9.941215
19     14.153847
20     18.121393
21     14.742065
22      6.514172
23     16.544028
24      8.140352
25     15.608022
26     14.967695
27     17.046336
28     19.399543
29      9.159298
         ...    
170     7.389574
171    14.376847
172     7.596578
173    11.960971
174    13.736152
175    24.783527
176    19.964023
177    12.174925
178    16.013845
179    12.378040
180    10.575090
181    13.933697
182     6.564088
183    24.163938
184    18.537950
185    20.779378
186     9.698685
187    17.060280
188    18.620098
189     6.051445
190    12.454978
191     8.405927
192     4.478859
193    18.448762
194    16.463191
195     5.364513
196     8.152376
197    12.7680

In [20]:
sales_predict_2=lm.predict(var_predictoras)
sales_predict_2

array([20.55546463, 12.34536229, 12.33701773, 17.61711596, 13.22390813,
       12.51208449, 11.71821241, 12.10551553,  3.7093792 , 12.55169696,
        7.0358597 , 17.25652015, 10.60866187,  8.81095051, 18.44466773,
       20.82891539, 12.90386507, 23.24107626,  9.94121476, 14.15384619,
       18.12139161, 14.74206357,  6.51417168, 16.54402663,  8.14035215,
       15.6080206 , 14.96769383, 17.0463346 , 19.39954145,  9.15929748,
       21.64292187, 11.35791808,  7.65045928, 18.83346334,  7.56302763,
       16.99280099, 23.36720719, 15.6258994 ,  9.91257829, 20.4405801 ,
       16.37872122, 17.29870935, 21.5621537 , 13.96692266,  8.9009974 ,
       15.16263814,  8.88644967, 21.69944046, 16.28690268,  8.18162949,
       12.64569407,  9.31962792, 20.66180115, 19.96126242, 20.35512357,
       21.30864743,  8.53774783, 12.76239488, 21.89072858, 18.10746914,
        5.74497097, 22.90418658, 16.78413768, 13.18474853, 16.96570907,
        7.82652846,  8.98703456, 12.02066194, 18.95313425, 21.09