# Metodo K-Means

In [2]:
import numpy as np

### Generamos Datos

In [3]:
data=np.random.random(90).reshape(30,3) #reshape(30 datos, 3 columnas)
data

array([[2.95819545e-02, 1.35300722e-01, 2.28026757e-01],
       [2.90527114e-01, 6.66902376e-01, 8.85923218e-02],
       [3.21594323e-01, 5.30101863e-01, 2.17008426e-01],
       [9.88916163e-01, 1.81585628e-01, 7.05553617e-01],
       [9.74649324e-01, 8.75929424e-01, 6.70901938e-01],
       [1.05872697e-01, 8.99602571e-01, 6.05107876e-02],
       [9.38174280e-02, 8.39909626e-01, 4.43139622e-01],
       [5.61267561e-01, 7.98484007e-02, 1.21068240e-01],
       [8.30097971e-02, 2.11156022e-01, 9.20912595e-01],
       [8.42730789e-01, 3.42080742e-02, 9.89429589e-01],
       [5.54786902e-01, 8.47263786e-01, 8.18266528e-01],
       [3.18993013e-02, 9.65116495e-01, 2.43100138e-01],
       [7.67582413e-01, 8.10919758e-01, 6.87806795e-01],
       [2.87753221e-02, 1.53826437e-01, 9.81237576e-01],
       [8.02504057e-02, 5.89231865e-01, 1.63534488e-01],
       [3.94337971e-01, 8.51607937e-01, 4.63750226e-01],
       [8.81110773e-03, 3.20197158e-01, 3.55666130e-01],
       [3.40811691e-01, 2.70490

### Creamos centroides (temporales) de los clusters

In [4]:
centroide_1=np.random.choice(range(len(data)))
centroide_2=np.random.choice(range(len(data)))
clust_centers=np.vstack((data[centroide_1],data[centroide_2]))
clust_centers

array([[0.25056881, 0.73619643, 0.6569291 ],
       [0.09381743, 0.83990963, 0.44313962]])

### Generamos clusters

In [5]:
from scipy.cluster.vq import vq

In [15]:
clusters=vq(data,clust_centers)
clusters[0].tolist() #array que dictaminna a que cluster pertenece cada dato
clusters[1].tolist() #distancias al varicentro del cluster

[0.7395089239917555,
 0.4408287621720966,
 0.4460924585964919,
 0.9247239022059225,
 0.7375724658666079,
 0.38744470860895375,
 0.0,
 0.9024817456291,
 0.6110897939055524,
 0.9767292528596785,
 0.3618209138962428,
 0.2439803470829967,
 0.5232973105902876,
 0.7025120240187611,
 0.37576912420296327,
 0.2670345761198636,
 0.5338339965036728,
 0.6640473854169059,
 0.6017300648864725,
 0.35597286661293776,
 0.4305410124616696,
 0.5560332261063239,
 0.7774593183789479,
 0.0,
 0.7643685014137045,
 0.9805240722182953,
 0.6015142384090701,
 0.5400850177108956,
 0.5734635936232702,
 0.2240913988615501]

In [7]:
from scipy.cluster.vq import kmeans

In [8]:
clusters_2=kmeans(data,2)
clusters_2 #caracteristicas de los varicentros de los 2 clusters

(array([[0.27146498, 0.57723536, 0.20199795],
        [0.52505944, 0.45989503, 0.76622581]]), 0.4107357892664791)